### DISCUSSION TITLE
Gradient positions not correct.

### DISCUSSION THREAD

**Discussion by remmob** [benjamin-dcs/gauge-card-pro#128] [Q&A] [answered]
![image](https://github.com/user-attachments/assets/f397e81a-23bd-49f5-83e8-341a322bb065)
With gradient property: false, it looks good 
![image](https://github.com/user-attachments/assets/caf64110-7837-4c99-aec8-3d578551fe5d)
With gradient property: true, the gradient is NOT correct.

```
                       - type: custom:gauge-card-pro
                          entity: sensor.solaredge_i3_ac_frequency
                          min: 47
                          max: 53
                          needle: true
                          needlde_color: "#FFFFFF"
                          gradient: true
                          gradient_resolution: high
                          titles:
                            primary: Net frequentie
                            primary_color: "#FFFFFF"
                            primary_font_size: 0.8em
                          value_texts:
                            #primary: "sensor.solaredge_i3_ac_frequency"
                            primary_unit: "Hz"
                            primary_color: "#FFFFFF"
                            secondary_color: "#FFFFFF"
                            primary_font_size_reduction: 12
                          segments:
                            - from: 47
                              color: "#ff0033" #red
                            - from: 48
                              color: "#4BB543" #green
                            - from: 52
                              color: "#ff0033" #red
                          card_mod:
                            style: |
                              ha-card {
                                border-radius: 0px 0px 15px 0px;
                                box-shadow: 0px 0px 3px 0px #0d141c;
                              }
```
I'm I missing something?
