### DISCUSSION TITLE
Integration for 3 sensors

### DISCUSSION THREAD

**Discussion by valimaties** [benjamin-dcs/gauge-card-pro#67] [Ideas]
Hi.
First of all, It looks awesome. Congrats for your custom control.

I have a temperature/humidity device which provides also the baterry state, so the percentage of remaining from baterry.
Do you think you can add the third entity to your control, to be able to display all those 3 states, temperature, humidity and baterry?

Thanks.

**Comment by benjamin-dcs** [comment]
One of my goals is to keep the card as clean as possible without 'overcluttering' with too much information. However one idea I haven't investigated yet is to add an icon in the 'upper-left' and/or 'upper-right' corner. This could be a way to solve your idea. I'm just not sure yet whether I find this suitable or not 😊

**Reply by valimaties** [reply]
This could be a quite "fixed" type of sensor, like battery one, as long as I see is very good to use your control to temperature and humidity sensors.
Think of it, is a very good idea to add a battery icon, like in entities card, which display the remaining battery percentage.

![image](https://github.com/user-attachments/assets/fd62ccdc-fe70-4042-a940-5701c73e0ae8)
![image](https://github.com/user-attachments/assets/05de1abb-044c-4d62-a48c-d40255916738)

**Comment by benjamin-dcs** [comment]
What's your thought about something like this:
<img width="261" alt="image" src="https://github.com/user-attachments/assets/a98896b4-3ba8-4179-b13d-ebda7f03e0bd" />

**Reply by valimaties** [reply]
This would be awesome. 
Could you add also a little label below it, displaying the percentage with digits? 🫣

**Reply by benjamin-dcs** [reply]
<img width="241" alt="image" src="https://github.com/user-attachments/assets/e3fca215-e260-40c6-bc53-cfda28c30828" />

**Reply by valimaties** [reply]
> <img width="241" alt="image" src="https://github.com/user-attachments/assets/e3fca215-e260-40c6-bc53-cfda28c30828" />
> 

Awesome 🥰

**Reply by Kawaland** [reply]
> <img alt="image" width="241" src="https://private-user-images.githubusercontent.com/78026082/445044123-e3fca215-e260-40c6-bc53-cfda28c30828.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDgwOTgxNTYsIm5iZiI6MTc0ODA5Nzg1NiwicGF0aCI6Ii83ODAyNjA4Mi80NDUwNDQxMjMtZTNmY2EyMTUtZTI2MC00MGM2LWJjNTMtY2ZkYTI4YzMwODI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNTI0VDE0NDQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiOTk5YmUyNWRiNTAwZTZjYWY1NGM2ZDA3Y2U0ZjFjMjBjMmU4ZWQ2MDllYTM1ODYyN2E5ZTE3NmVmOTBhMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KIjhxOqK44Wa0pPlGbBmDZLJniApn6J_rioIe_aOc4U">

Very Nice and usefull ie to manage Battery with Solar prod and power consumption

**Reply by benjamin-dcs** [reply]
> > <img alt="image" width="241" src="https://private-user-images.githubusercontent.com/78026082/445044123-e3fca215-e260-40c6-bc53-cfda28c30828.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDgwOTgxNTYsIm5iZiI6MTc0ODA5Nzg1NiwicGF0aCI6Ii83ODAyNjA4Mi80NDUwNDQxMjMtZTNmY2EyMTUtZTI2MC00MGM2LWJjNTMtY2ZkYTI4YzMwODI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNTI0VDE0NDQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiOTk5YmUyNWRiNTAwZTZjYWY1NGM2ZDA3Y2U0ZjFjMjBjMmU4ZWQ2MDllYTM1ODYyN2E5ZTE3NmVmOTBhMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KIjhxOqK44Wa0pPlGbBmDZLJniApn6J_rioIe_aOc4U">
> 
> Very Nice and usefull ie to manage Battery with Solar prod and power consumption

Great to see you like it, thanks for leaving a comment and your star 🌟!

**Reply by valimaties** [reply]
I just updated the control. But I think I have some issues adding the battery sensor. More than that, the font size does not do anything, the size of texts are the same no matter what size I set. What I'm doing wrong?

```
type: custom:gauge-card-pro
segments:
  - from: 0
    color: red
  - from: 25
    color: "#FFA500"
  - from: 50
    color: rgb(255, 255, 0)
  - from: 100
    color: var(--green-color)
needle: true
gradient: true
titles:
  primary: "{{ state_attr(entity, 'friendly_name') }}"
  primary_font_size: "7"
  secondary_font_size: "5"
  secondary: |
    {{ state_attr(entity2, 'friendly_name') }}
gradient_resolution: medium
entity: sensor.bibi_temperatura
inner:
  mode: severity
  gradient: true
  gradient_resolution: medium
  min: 30
  max: 70
value_texts:
  primary: ""
  primary_font_size_reduction: 2.5
hide_background: false
min: 15
max: 35
entity2: sensor.bibi_umiditate
```

The code was generated by UI controls, I've just enabled yaml code, copy it and pasted here.
Where do I have to add the battery sensor ( `sensor.bibi_baterie`).

**Edit**

I found it, as a `code add` object, not by UI controls.
I had to add 
```
icon:
  battery: sensor.bibi_baterie
```
and here it is...
![image](https://github.com/user-attachments/assets/f7d3edde-96a9-472d-9b4a-557dd3ad936f)

However, the font sizes does not work for me, it is the same font size no matter what values I set for them.
