### ISSUE TITLE
Visual Editor: Tap_action and other actions

### ISSUE THREAD

**Issue by better-tester** [benjamin-dcs/gauge-card-pro#111]
What I do: 
first entity -> charging power
second entity -> discharging power
setpoint -> charging state

All works fine

What I want to do, did and it works:

tap_action -> more-info of first entity (default)
double_tap_action -> more-info of second entity
hold_action -> more-info of charging state

In yaml 
```
double_tap_action:
  entity: sensor.solarnet_entladeleistung
  action: more-info
hold_action:
  entity: sensor.byd_battery_box_premium_hv_ladezustand
  action: more-info
```
This works perfectly but the visual editor is out of the game. I'm fine with yaml.
The message is:

> At path: hold_action.entity -- Expected a value of type `**never**`, but received: `"sensor.byd_battery_box_premium_hv_ladezustand"`

Against the expectation of the implementation it does what I expected :-)
