### ISSUE TITLE
Add small needles to show min/max for today

### ISSUE THREAD

**Issue by scp93ch** [benjamin-dcs/gauge-card-pro#118]
For a few gauges I would like to be able to see at a glance the current value and the min/max values for today.

Ideally the actual values (not just the needles) would also be shown in the card (top left and top right?).

I don't know if this is useful for others, or fits with your plans, but I thought I would ask. Thank you.

**Comment by benjamin-dcs** [comment]
This was actually the reason that I added `static` mode for the inner gauge such that you can create something like this:

![Image](https://github.com/user-attachments/assets/e7b38ba5-6734-49b6-ad54-3d948eefc22e)

Is that something you can work with or do you also need the inner gauge as well? Showing min/max values "somewhere" is definitely something I am thinking about. I just haven't found a satisfying way/place to show them.

**Comment by scp93ch** [comment]
I didn't know you could do that. It's certainly useful as I am not using the inner gauge for anything. I primarily want the min/max numbers somewhere but using the inner gauge certainly helps.

If you had a moment, it would be useful to see the yaml for an entity and it's daily min/max shown as above. Thanks.

**Comment by oxc** [comment]
I personally was hoping for a solution visually more to what you produced with the inner segments above, just on the outer side of the gauge, or even both 😄 

I could also imagine the outer/inner part of the main gauge to dim and only show the "min-max" part in full saturation/opacity. But those are all very taste-specific suggestions, I'm not sure there is a one-size-fits-all solution.

For me, greater flexibility, for example by being able to create an arbitrary number of stacked gauges and needles would be a welcome solution.
Then I would probably create an inner and outer "range indicator" gauge like in your example above, and keep the needles as is

**Comment by benjamin-dcs** [comment]
Just some quick brainfarts:

![Image](https://github.com/user-attachments/assets/90642c3c-1ffc-4d7a-8fc7-e02fd3e1fa71)

![Image](https://github.com/user-attachments/assets/e210348d-e892-4b5b-9a83-a6fbbb67d232)

![Image](https://github.com/user-attachments/assets/03b6350f-566e-4363-8cb1-9125fd39f945)

The second and third are (clearly) the same shape, just different colors/transparency. Color/transparency is something you can change for the current needles already anyway. What do you think?

**Comment by scp93ch** [comment]
I just realised I can get the `max` data in the card text:

```yaml
type: custom:gauge-card-pro
entity: sensor.givtcp_sa2245g349_load_power
segments:
  - from: 0
    color: var(--success-color)
  - from: 5000
    color: var(--warning-color)
  - from: 10000
    color: var(--error-color)
needle: true
gradient: true
titles:
  primary: |
    {% set max = states('sensor.house_load_power_max_24h') %}
    Load ({{ max | round }}W max)
gradient_resolution: medium
max: 10000
inner:
  mode: static
  segments: |
    {% set min = states('sensor.house_load_power_min_24h') %}
    {% set max = states('sensor.house_load_power_max_24h') %}
    {{
      [
        { "from": 0, "color": "var(--card-background-color)" },
        { "from": min, "color": "var(--info-color)" },
        { "from": max, "color": "var(--card-background-color)" }
      ]
    }}
grid_options:
  columns: 8
  rows: 3
```

This gives:

![Image](https://github.com/user-attachments/assets/56b1f58b-e2ce-4bcb-b8c5-7c6505246777)

Obviously, the `min` could also be added if required.
