### ISSUE TITLE
Color gradients without needle

### ISSUE THREAD

**Issue by wolfstar-bs** [benjamin-dcs/gauge-card-pro#139]
Is support for color gradients also possible without a needle?
I would like to display some gauges without a needle, but still retain the color gradient. Is there any way to add this?

Best regards, Wolfgang

**Comment by benjamin-dcs** [comment]
Currently only for the inner-gauge (use `mode: static`).

Are you looking for this feature on the main-gauge? If so, what's you use-case?

**Comment by benjamin-dcs** [comment]
For now you can use `card_mod` to hide the main needle:

```yaml
card_mod:
  style:
    gauge-card-pro-gauge $: |
      .needle {
        display: none;
      }
```

In the next update I'm also implementing the ability to customize the shape of some elements, including the needle. This will also allow 'none', which will hide the needle.
