### ISSUE TITLE
Remove irratic rotation of inner gauge on refresh

### ISSUE THREAD

**Issue by benjamin-dcs** [benjamin-dcs/gauge-card-pro#39]
Not sure yet why this is happening -> Looking for reliable reproduction path

![Image](https://github.com/user-attachments/assets/01d59098-664b-4bb2-8788-7494cbcb9207)

**Comment by quiggles** [comment]
Maybe worth sharing your card code

**Comment by benjamin-dcs** [comment]
This is one I'm seeing the behaviour regularly:


```yaml
type: custom:gauge-card-pro
entity: sensor.ikea_vindstyrka_kantoor_voc_index
entity2: sensor.ikea_vindstyrka_kantoor_temperature
needle: true
min: "0"
max: "450"
value: "{{ states(entity) | float(0) }}"
inner:
  value_text: "{{ states(entity2) }}°C"
  value: "{{ states(entity2) }}"
  min: 15
  max: 25
gradient: true
gradient_resolution: medium
primary: |-
  {% set value = states(entity) | float %}
  {% if value > 351 %}
  Extremely polluted
  {% elif value > 251 %}
  Severely polluted
  {% elif value > 200 %}
  Heavily polluted
  {% elif value > 150 %}
  Moderately polluted
  {% elif value > 100 %}
  Lightly polluted 
  {% elif value > 50 %}
  Good
  {% else %}
  Excellent
  {% endif %}
secondary_color: "#aaaaaa"
value_text: "{{ states(entity) | float(0) }}"
hide_background: true
secondary: Office
grid_options:
  columns: 9
  rows: auto
segments:
  - from: 0
    color: "#4caf50"
  - from: 62.5
    color: "#8bc34a"
  - from: 125
    color: "#ffeb3b"
  - from: 175
    color: "#ff9800"
  - from: 225
    color: "#f44336"
  - from: 300
    color: "#926bc7"
  - from: 400
    color: "#795548"
```
